"""Pokeball Registry API — accepts submissions, creates PRs on GitHub."""
import os
import json
import hashlib
import asyncio
from datetime import datetime, timezone
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path
import urllib.request
import urllib.error

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
REGISTRY_REPO = os.environ.get("REGISTRY_REPO", "DeepBlueDynamics/nemesis8-pokeballs")
PORT = int(os.environ.get("PORT", "8080"))


def github_api(method, path, body=None):
    """Call GitHub API."""
    url = f"https://api.github.com{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {GITHUB_TOKEN}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("Content-Type", "application/json")
    req.add_header("User-Agent", "pokeball-registry")
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        error_body = e.read().decode() if e.fp else ""
        return {"error": f"{e.code}: {error_body}"}


def create_pr(name, spec_content, submitter, description):
    """Create a PR on the registry repo with the pokeball spec."""
    # Get default branch SHA
    repo_info = github_api("GET", f"/repos/{REGISTRY_REPO}")
    if "error" in repo_info:
        # Repo might not exist — create it
        org, repo_name = REGISTRY_REPO.split("/")
        github_api("POST", f"/orgs/{org}/repos", {
            "name": repo_name,
            "description": "Pokeball registry — sealed container specs for nemesis8",
            "auto_init": True,
        })
        repo_info = github_api("GET", f"/repos/{REGISTRY_REPO}")

    default_branch = repo_info.get("default_branch", "main")
    ref_info = github_api("GET", f"/repos/{REGISTRY_REPO}/git/ref/heads/{default_branch}")
    if "error" in ref_info:
        return {"error": f"cannot read main branch: {ref_info['error']}"}
    base_sha = ref_info["object"]["sha"]

    # Create branch
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch = f"pokeball/{name}-{ts}"
    result = github_api("POST", f"/repos/{REGISTRY_REPO}/git/refs", {
        "ref": f"refs/heads/{branch}",
        "sha": base_sha,
    })
    if "error" in result:
        return {"error": f"cannot create branch: {result['error']}"}

    # Create/update file
    import base64
    content_b64 = base64.b64encode(spec_content.encode()).decode()
    file_path = f"{name}/pokeball.yaml"
    commit_msg = f"Add pokeball: {name}"
    if description:
        commit_msg += f"\n\n{description}"
    if submitter:
        commit_msg += f"\n\nSubmitted by: {submitter}"

    result = github_api("PUT", f"/repos/{REGISTRY_REPO}/contents/{file_path}", {
        "message": commit_msg,
        "content": content_b64,
        "branch": branch,
    })
    if "error" in result:
        return {"error": f"cannot commit file: {result['error']}"}

    # Create PR
    pr_body = f"## Pokeball: {name}\n\n"
    if description:
        pr_body += f"{description}\n\n"
    if submitter:
        pr_body += f"Submitted by: {submitter}\n"
    pr_body += f"\nGenerated by nemesis8 pokeball registry"

    pr = github_api("POST", f"/repos/{REGISTRY_REPO}/pulls", {
        "title": f"Add pokeball: {name}",
        "head": branch,
        "base": default_branch,
        "body": pr_body,
    })

    if "error" in pr:
        return {"error": f"cannot create PR: {pr['error']}"}

    return {
        "pr_url": pr.get("html_url", ""),
        "pr_number": pr.get("number", 0),
        "branch": branch,
        "status": "submitted",
    }


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/health":
            self.send_json(200, {"status": "ok", "service": "pokeball-registry"})
        elif self.path == "/pokeballs":
            # List pokeballs in registry
            result = github_api("GET", f"/repos/{REGISTRY_REPO}/contents/")
            if isinstance(result, list):
                pokeballs = [
                    item["name"] for item in result
                    if item["type"] == "dir" and not item["name"].startswith(".")
                ]
                self.send_json(200, {"pokeballs": pokeballs})
            else:
                self.send_json(200, {"pokeballs": [], "note": "registry empty or not found"})
        elif self.path.startswith("/pokeballs/"):
            name = self.path.split("/pokeballs/")[1].strip("/")
            if not name:
                self.send_json(400, {"error": "missing pokeball name"})
                return
            result = github_api("GET", f"/repos/{REGISTRY_REPO}/contents/{name}/pokeball.yaml")
            if "error" in result or "content" not in result:
                self.send_json(404, {"error": f"pokeball '{name}' not found"})
            else:
                import base64
                content = base64.b64decode(result["content"]).decode()
                self.send_json(200, {"name": name, "spec": content})
        else:
            self.send_json(404, {"error": "not found"})

    def do_POST(self):
        if self.path == "/submit":
            length = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(length)) if length > 0 else {}

            name = body.get("name", "").strip()
            spec = body.get("spec", "").strip()
            submitter = body.get("submitter", "anonymous")
            description = body.get("description", "")

            if not name:
                self.send_json(400, {"error": "missing 'name'"})
                return
            if not spec:
                self.send_json(400, {"error": "missing 'spec' (pokeball.yaml content)"})
                return
            if not GITHUB_TOKEN:
                self.send_json(500, {"error": "GITHUB_TOKEN not configured"})
                return

            result = create_pr(name, spec, submitter, description)
            if "error" in result:
                self.send_json(500, result)
            else:
                self.send_json(201, result)
        else:
            self.send_json(404, {"error": "not found"})

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def send_json(self, code, obj):
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(json.dumps(obj).encode())

    def log_message(self, format, *args):
        print(f"[{datetime.now(timezone.utc).isoformat()}] {args[0]}")


if __name__ == "__main__":
    print(f"Pokeball Registry API listening on :{PORT}")
    print(f"Registry repo: {REGISTRY_REPO}")
    HTTPServer(("0.0.0.0", PORT), Handler).serve_forever()
