use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::path::Path;

use super::spec::PokeballSpec;
use super::store::PokeballStore;
use crate::docker::DockerOps;

/// Generate a hardened multi-stage Dockerfile from a PokeballSpec
pub fn generate_dockerfile(spec: &PokeballSpec) -> String {
    let mut df = String::with_capacity(2048);

    // ── Stage 1: builder ──
    writeln!(df, "# Auto-generated by nemisis8 pokeball").unwrap();
    writeln!(df, "# Spec: {} ({})", spec.metadata.name, spec.api_version).unwrap();
    writeln!(df).unwrap();
    writeln!(df, "FROM {} AS builder", spec.runtime.base_image).unwrap();
    writeln!(df).unwrap();

    // System packages
    if !spec.build.system_packages.is_empty() {
        let pkgs = spec.build.system_packages.join(" ");
        writeln!(df, "RUN apt-get update && apt-get install -y --no-install-recommends \\").unwrap();
        writeln!(df, "    {pkgs} \\").unwrap();
        writeln!(df, "    && rm -rf /var/lib/apt/lists/*").unwrap();
        writeln!(df).unwrap();
    }

    // Enable corepack for pnpm/yarn
    if let Some(ref pm) = spec.runtime.package_manager {
        if pm == "pnpm" || pm == "yarn" {
            writeln!(df, "RUN corepack enable").unwrap();
            writeln!(df).unwrap();
        }
    }

    writeln!(df, "WORKDIR /build").unwrap();
    writeln!(df).unwrap();

    // Copy dependency manifests first (for caching)
    match spec.runtime.language.as_str() {
        "typescript" | "javascript" => {
            writeln!(df, "# Copy dependency manifests for layer caching").unwrap();
            writeln!(df, "COPY package.json ./").unwrap();
            if let Some(ref pm) = spec.runtime.package_manager {
                match pm.as_str() {
                    "pnpm" => writeln!(df, "COPY pnpm-lock.yaml ./").unwrap(),
                    "yarn" => writeln!(df, "COPY yarn.lock ./").unwrap(),
                    "bun" => {
                        // bun.lockb or bun.lock
                        writeln!(df, "COPY bun.lock* bun.lockb* ./").unwrap();
                    }
                    _ => writeln!(df, "COPY package-lock.json* ./").unwrap(),
                }
            }
            writeln!(df).unwrap();
        }
        "python" => {
            writeln!(df, "COPY requirements*.txt pyproject.toml* ./").unwrap();
            writeln!(df).unwrap();
        }
        "rust" => {
            writeln!(df, "COPY Cargo.toml Cargo.lock* ./").unwrap();
            writeln!(df).unwrap();
        }
        "go" => {
            writeln!(df, "COPY go.mod go.sum* ./").unwrap();
            writeln!(df).unwrap();
        }
        _ => {}
    }

    // Install dependencies
    if let Some(ref cmd) = spec.build.install_cmd {
        writeln!(df, "RUN {cmd}").unwrap();
        writeln!(df).unwrap();
    }

    // Copy full source
    writeln!(df, "COPY . .").unwrap();
    writeln!(df).unwrap();

    // Build
    if let Some(ref cmd) = spec.build.build_cmd {
        writeln!(df, "RUN {cmd}").unwrap();
        writeln!(df).unwrap();
    }

    // ── Stage 2: runtime ──
    writeln!(df, "# ── Runtime stage ──").unwrap();
    writeln!(df, "FROM {} AS runtime", spec.runtime.base_image).unwrap();
    writeln!(df).unwrap();

    // System packages in runtime too (some needed at runtime)
    let runtime_pkgs: Vec<&str> = spec
        .build
        .system_packages
        .iter()
        .filter(|p| *p != "git") // git not needed at runtime
        .map(|s| s.as_str())
        .collect();

    if !runtime_pkgs.is_empty() {
        let pkgs = runtime_pkgs.join(" ");
        writeln!(df, "RUN apt-get update && apt-get install -y --no-install-recommends \\").unwrap();
        writeln!(df, "    {pkgs} \\").unwrap();
        writeln!(df, "    && rm -rf /var/lib/apt/lists/*").unwrap();
        writeln!(df).unwrap();
    }

    // Create pokeball user
    writeln!(
        df,
        "RUN groupadd -r pokeball && useradd -r -g pokeball -d /work -s /bin/bash pokeball"
    )
    .unwrap();
    writeln!(df).unwrap();

    // Create directories
    writeln!(df, "RUN mkdir -p /work /comms/inbox /comms/outbox /comms/status /tmp \\").unwrap();
    writeln!(df, "    && chown -R pokeball:pokeball /work /comms /tmp").unwrap();
    writeln!(df).unwrap();

    // Copy built artifacts from builder
    writeln!(df, "COPY --from=builder --chown=pokeball:pokeball /build /work").unwrap();
    writeln!(df).unwrap();

    // Copy worker binary (must be built and available in context)
    writeln!(df, "# Worker binary is bind-mounted or copied at runtime").unwrap();
    writeln!(df).unwrap();

    writeln!(df, "WORKDIR /work").unwrap();
    writeln!(df, "USER pokeball").unwrap();
    writeln!(df).unwrap();

    writeln!(df, "ENTRYPOINT [\"tini\", \"--\"]").unwrap();
    writeln!(df, "CMD [\"sleep\", \"infinity\"]").unwrap();

    df
}

/// Build a pokeball image from its spec.
/// Returns the image tag.
pub async fn build_pokeball(spec: &PokeballSpec, store: &PokeballStore) -> Result<String> {
    let pokeball_dir = store.pokeball_dir(&spec.metadata.name);
    std::fs::create_dir_all(&pokeball_dir)
        .context("creating pokeball directory")?;

    // Save spec
    spec.save(&pokeball_dir.join("pokeball.yaml"))?;

    // Generate Dockerfile
    let dockerfile_content = generate_dockerfile(spec);
    let dockerfile_path = pokeball_dir.join("Dockerfile");
    std::fs::write(&dockerfile_path, &dockerfile_content)
        .context("writing generated Dockerfile")?;

    // Build context = project source directory
    let source_path = Path::new(spec.source.local_path());
    if !source_path.is_dir() {
        anyhow::bail!(
            "source path does not exist: {}",
            spec.source.local_path()
        );
    }

    // Write Dockerfile into the source dir temporarily for build context
    // (or use a separate build context approach)
    let temp_dockerfile = source_path.join("Dockerfile.pokeball");
    std::fs::write(&temp_dockerfile, &dockerfile_content)
        .context("writing temp Dockerfile to source")?;

    // Build using bollard
    let image_tag = spec.image_tag();
    let docker = DockerOps::new(Some(&image_tag))?;

    let result = build_image_from_dir(
        &docker,
        source_path,
        "Dockerfile.pokeball",
        &image_tag,
    )
    .await;

    // Clean up temp dockerfile
    let _ = std::fs::remove_file(&temp_dockerfile);

    result?;

    // Save the built image tag
    std::fs::write(pokeball_dir.join("image_tag"), &image_tag)
        .context("saving image tag")?;

    Ok(image_tag)
}

/// Build a Docker image from a directory with a custom Dockerfile name
async fn build_image_from_dir(
    docker: &DockerOps,
    context_dir: &Path,
    dockerfile: &str,
    tag: &str,
) -> Result<()> {
    use bollard::image::BuildImageOptions;

    let tar_body = crate::docker::create_tar_context(context_dir, None)
        .context("creating build context")?;

    let options = BuildImageOptions {
        dockerfile: dockerfile.to_string(),
        t: tag.to_string(),
        rm: true,
        ..Default::default()
    };

    let mut stream = docker
        .docker()
        .build_image(options, None, Some(tar_body.into()));

    while let Some(result) = futures_util::StreamExt::next(&mut stream).await {
        match result {
            Ok(info) => {
                if let Some(text) = info.stream {
                    let line = text.trim_end();
                    if !line.is_empty() {
                        eprintln!("{line}");
                    }
                }
                if let Some(error) = info.error {
                    anyhow::bail!("Docker build error: {error}");
                }
            }
            Err(e) => anyhow::bail!("Docker build stream error: {e}"),
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pokeball::spec::PokeballSpec;

    #[test]
    fn test_generate_dockerfile_node() {
        let mut spec = PokeballSpec::default_for("test", "/tmp/test");
        spec.runtime.language = "typescript".to_string();
        spec.runtime.base_image = "node:22-bookworm-slim".to_string();
        spec.runtime.package_manager = Some("pnpm".to_string());
        spec.build.install_cmd = Some("pnpm install --frozen-lockfile".to_string());
        spec.build.build_cmd = Some("pnpm build".to_string());

        let df = generate_dockerfile(&spec);
        assert!(df.contains("FROM node:22-bookworm-slim AS builder"));
        assert!(df.contains("corepack enable"));
        assert!(df.contains("pnpm-lock.yaml"));
        assert!(df.contains("pnpm install --frozen-lockfile"));
        assert!(df.contains("pnpm build"));
        assert!(df.contains("USER pokeball"));
        assert!(df.contains("/comms/inbox"));
    }

    #[test]
    fn test_generate_dockerfile_python() {
        let mut spec = PokeballSpec::default_for("pyapp", "/tmp/pyapp");
        spec.runtime.language = "python".to_string();
        spec.runtime.base_image = "python:3.12-slim-bookworm".to_string();
        spec.build.install_cmd = Some("pip install -r requirements.txt".to_string());

        let df = generate_dockerfile(&spec);
        assert!(df.contains("FROM python:3.12-slim-bookworm AS builder"));
        assert!(df.contains("requirements*.txt"));
        assert!(df.contains("pip install"));
    }

    #[test]
    fn test_generate_dockerfile_rust() {
        let mut spec = PokeballSpec::default_for("rsapp", "/tmp/rsapp");
        spec.runtime.language = "rust".to_string();
        spec.runtime.base_image = "rust:1-bookworm".to_string();
        spec.build.install_cmd = Some("cargo fetch".to_string());
        spec.build.build_cmd = Some("cargo build --release".to_string());

        let df = generate_dockerfile(&spec);
        assert!(df.contains("FROM rust:1-bookworm AS builder"));
        assert!(df.contains("Cargo.toml"));
        assert!(df.contains("cargo build --release"));
    }
}
