use crate::app_def::AppDef;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Directory inside the Docker image where app TOMLs are stored.
const BUILTIN_APPS_DIR: &str = "/opt/defaults/apps";

// Compiled-in app TOMLs — available on the host binary even without the Docker
// image. GENERATED by build.rs from apps/*.toml (mirrors services/providers).
include!(concat!(env!("OUT_DIR"), "/embedded_apps.rs"));

/// Registry of all known apps (builtins + user-defined).
pub struct AppRegistry {
    apps: HashMap<String, AppDef>,
}

impl AppRegistry {
    /// Build from the builtin apps dir (Docker image / dev override), else the
    /// compiled-in TOMLs, then overlay `~/.nemesis8/apps/*.toml`.
    pub fn load() -> Self {
        let mut reg = Self {
            apps: HashMap::new(),
        };

        let builtin_dir = builtin_apps_dir();
        if builtin_dir.is_dir() {
            reg.load_apps_from_dir(&builtin_dir);
        } else {
            reg.load_embedded();
        }
        reg.load_user_apps();
        reg
    }

    fn load_embedded(&mut self) {
        for toml_str in EMBEDDED_APPS {
            match toml::from_str::<AppDef>(toml_str) {
                Ok(def) => {
                    self.apps.insert(def.app.name.to_lowercase(), def);
                }
                Err(e) => {
                    eprintln!("[nemesis8] warning: failed to parse embedded app: {e}");
                }
            }
        }
    }

    fn load_apps_from_dir(&mut self, dir: &Path) {
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(e) => {
                eprintln!(
                    "[nemesis8] warning: could not read apps dir {}: {e}",
                    dir.display()
                );
                return;
            }
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "toml") {
                continue;
            }
            self.load_app_file(&path);
        }
    }

    fn load_app_file(&mut self, path: &Path) {
        match std::fs::read_to_string(path) {
            Ok(content) => match toml::from_str::<AppDef>(&content) {
                Ok(def) => {
                    self.apps.insert(def.app.name.to_lowercase(), def);
                }
                Err(e) => {
                    eprintln!("[nemesis8] warning: failed to parse {}: {e}", path.display());
                }
            },
            Err(e) => {
                eprintln!("[nemesis8] warning: could not read {}: {e}", path.display());
            }
        }
    }

    fn load_user_apps(&mut self) {
        let user_dir = dirs::home_dir()
            .map(|h| h.join(".nemesis8").join("apps"))
            .unwrap_or_default();
        if !user_dir.is_dir() {
            return;
        }
        let entries = match std::fs::read_dir(&user_dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "toml") {
                continue;
            }
            self.load_app_file(&path);
        }
    }

    /// Look up an app by name (case-insensitive).
    pub fn get(&self, name: &str) -> Option<&AppDef> {
        self.apps.get(&name.to_lowercase())
    }

    /// Resolve an app name, with a helpful error listing the known ones.
    pub fn resolve(&self, name: &str) -> Result<&AppDef, String> {
        self.get(name).ok_or_else(|| {
            format!("unknown app '{}'. Available: {}", name, self.names().join(", "))
        })
    }

    /// Iterate all registered apps.
    pub fn all(&self) -> impl Iterator<Item = &AppDef> {
        self.apps.values()
    }

    /// All registered app names, sorted.
    pub fn names(&self) -> Vec<String> {
        let mut names: Vec<String> = self.apps.keys().cloned().collect();
        names.sort();
        names
    }
}

/// Builtin apps dir. Honors NEMESIS8_APPS_DIR (tests) then the image path.
fn builtin_apps_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("NEMESIS8_APPS_DIR") {
        return PathBuf::from(dir);
    }
    PathBuf::from(BUILTIN_APPS_DIR)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn load_test_registry() -> AppRegistry {
        let apps_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("apps");
        unsafe {
            std::env::set_var("NEMESIS8_APPS_DIR", &apps_dir);
        }
        AppRegistry::load()
    }

    #[test]
    fn test_load_glint() {
        let reg = load_test_registry();
        assert!(reg.get("glint").is_some());
        assert!(reg.get("GLINT").is_some()); // case-insensitive
    }

    #[test]
    fn test_resolve_error() {
        let reg = load_test_registry();
        let err = reg.resolve("nope").unwrap_err();
        assert!(err.contains("unknown app"));
        assert!(err.contains("glint"));
    }

    #[test]
    fn test_names_nonempty() {
        let reg = load_test_registry();
        assert!(reg.names().iter().any(|n| n == "glint"));
    }
}
