use crate::capsule_def::CapsuleDef;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Directory inside the Docker image where capsule TOMLs are stored.
const BUILTIN_CAPSULES_DIR: &str = "/opt/defaults/capsules";

// Compiled-in capsule TOMLs — available on the host binary even without the
// Docker image. GENERATED by build.rs from capsules/*.toml (mirrors services).
include!(concat!(env!("OUT_DIR"), "/embedded_capsules.rs"));

/// Registry of all known capsules (builtins + user-defined).
pub struct CapsuleRegistry {
    capsules: HashMap<String, CapsuleDef>,
}

impl CapsuleRegistry {
    /// Build from the builtin capsules dir (Docker image / dev override), else
    /// the compiled-in TOMLs, then overlay `~/.nemesis8/capsules/*.toml`.
    pub fn load() -> Self {
        let mut reg = Self {
            capsules: HashMap::new(),
        };

        let builtin_dir = builtin_capsules_dir();
        if builtin_dir.is_dir() {
            reg.load_capsules_from_dir(&builtin_dir);
        } else {
            reg.load_embedded();
        }
        reg.load_user_capsules();
        reg
    }

    fn load_embedded(&mut self) {
        for toml_str in EMBEDDED_CAPSULES {
            match toml::from_str::<CapsuleDef>(toml_str) {
                Ok(def) => {
                    self.capsules.insert(def.capsule.name.to_lowercase(), def);
                }
                Err(e) => {
                    eprintln!("[nemesis8] warning: failed to parse embedded capsule: {e}");
                }
            }
        }
    }

    fn load_capsules_from_dir(&mut self, dir: &Path) {
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(e) => {
                eprintln!(
                    "[nemesis8] warning: could not read capsules dir {}: {e}",
                    dir.display()
                );
                return;
            }
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "toml") {
                continue;
            }
            self.load_capsule_file(&path);
        }
    }

    fn load_capsule_file(&mut self, path: &Path) {
        match std::fs::read_to_string(path) {
            Ok(content) => match toml::from_str::<CapsuleDef>(&content) {
                Ok(def) => {
                    self.capsules.insert(def.capsule.name.to_lowercase(), def);
                }
                Err(e) => {
                    eprintln!("[nemesis8] warning: failed to parse {}: {e}", path.display());
                }
            },
            Err(e) => {
                eprintln!("[nemesis8] warning: could not read {}: {e}", path.display());
            }
        }
    }

    fn load_user_capsules(&mut self) {
        let user_dir = dirs::home_dir()
            .map(|h| h.join(".nemesis8").join("capsules"))
            .unwrap_or_default();
        if !user_dir.is_dir() {
            return;
        }
        let entries = match std::fs::read_dir(&user_dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "toml") {
                continue;
            }
            self.load_capsule_file(&path);
        }
    }

    /// Look up a capsule by name (case-insensitive).
    pub fn get(&self, name: &str) -> Option<&CapsuleDef> {
        self.capsules.get(&name.to_lowercase())
    }

    /// Resolve a capsule name, with a helpful error listing the known ones.
    pub fn resolve(&self, name: &str) -> Result<&CapsuleDef, String> {
        self.get(name).ok_or_else(|| {
            format!("unknown capsule '{}'. Available: {}", name, self.names().join(", "))
        })
    }

    /// Iterate all registered capsules.
    pub fn all(&self) -> impl Iterator<Item = &CapsuleDef> {
        self.capsules.values()
    }

    /// All registered capsule names, sorted.
    pub fn names(&self) -> Vec<&str> {
        let mut names: Vec<&str> = self.capsules.keys().map(|s| s.as_str()).collect();
        names.sort();
        names
    }
}

/// Builtin capsules dir. Honors NEMESIS8_CAPSULES_DIR (tests) then the image path.
fn builtin_capsules_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("NEMESIS8_CAPSULES_DIR") {
        return PathBuf::from(dir);
    }
    PathBuf::from(BUILTIN_CAPSULES_DIR)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn load_test_registry() -> CapsuleRegistry {
        let capsules_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("capsules");
        unsafe {
            std::env::set_var("NEMESIS8_CAPSULES_DIR", &capsules_dir);
        }
        CapsuleRegistry::load()
    }

    #[test]
    fn test_load_sigil() {
        let reg = load_test_registry();
        assert!(reg.get("sigil").is_some());
        assert!(reg.get("SIGIL").is_some()); // case-insensitive
    }

    #[test]
    fn test_resolve_error() {
        let reg = load_test_registry();
        let err = reg.resolve("nope").unwrap_err();
        assert!(err.contains("unknown capsule"));
    }
}
