//! Ferricula identity discovery — Docker-labelled identity containers (Steve
//! and friends) become MCP servers an agent can be given.
//!
//! A Ferricula v2/v3 identity is one server process in one container. Instead
//! of asking the user to hand-register each one, the launcher asks Docker:
//! every container carrying the `ferricula.identity` label is an identity. For
//! each running one n8 keeps a server definition current, one of two ways:
//!
//! - **http** — the container serves Streamable-HTTP MCP itself (`POST /mcp`).
//!   n8 drops a server TOML into the user MCP dir the container already reads
//!   (`<data_home>/.nemesis8/mcp`, see [`crate::mcp_registry::host_user_mcp_dir`]).
//! - **bridge** — the identity ships a stdio bridge script (label
//!   `ferricula.bridge`, a Python file speaking MCP over stdio and REST to the
//!   identity). n8 copies it into the user tool dir (`<data_home>/mcp`, the
//!   same place `n8 mcp add` puts a `.py` tool) as `ferricula-<name>.py` with
//!   a small header that points it at the identity through
//!   `host.docker.internal` and at a token file n8 writes from the keychain.
//!
//! The bridge is used when the container's `/mcp` answers 404 (an older image)
//! and a bridge is labelled; otherwise http.
//!
//! **Enabling is opt-in.** Discovery makes an identity *available* — it shows
//! in `n8 mcp list` and the tools picker — but an agent is only given it when
//! its workspace lists the identity's name in `mcp_tools` (or the picker
//! toggles it). An identity's bearer may carry real power (Steve's operator
//! token writes his memory), so nothing is handed to every agent by default.
//! `[integrations] ferricula_auto_enable = true` restores give-to-all.
//! When enabled, the token env goes on `env_imports`, so the bearer is
//! forwarded from the keychain like any imported secret. No image rebuild.
//!
//! Discovery talks to the Docker API through the crate's existing client, not
//! the `docker` CLI, so no container-supplied value ever reaches a command line.
//!
//! Label contract (set on the identity's container, e.g. in its run script or
//! compose file):
//!
//! | label | meaning | default |
//! |---|---|---|
//! | `ferricula.identity` | the identity's short name; becomes the MCP server name | required |
//! | `ferricula.mcp_port` | HOST port the identity is published on | first published port |
//! | `ferricula.mcp_path` | path of the Streamable-HTTP MCP endpoint | `/mcp` |
//! | `ferricula.bridge` | stdio bridge script; a relative path is under the compose project dir | none |
//! | `ferricula.token_env` | env var holding the bearer token (forwarded from the keychain) | `FERRICULA_OPERATOR_TOKEN` |
//! | `ferricula.health_path` | unauthenticated route reporting `agent_id` and `mode` | `/health` |
//!
//! Opt out of discovery entirely with `[integrations] ferricula_discovery = false`.

use bollard::models::ContainerSummary;
use serde::Serialize;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

pub const LABEL_IDENTITY: &str = "ferricula.identity";
pub const LABEL_PORT: &str = "ferricula.mcp_port";
pub const LABEL_PATH: &str = "ferricula.mcp_path";
pub const LABEL_BRIDGE: &str = "ferricula.bridge";
pub const LABEL_TOKEN_ENV: &str = "ferricula.token_env";
pub const LABEL_HEALTH: &str = "ferricula.health_path";
const LABEL_COMPOSE_DIR: &str = "com.docker.compose.project.working_dir";
pub const DEFAULT_TOKEN_ENV: &str = "FERRICULA_OPERATOR_TOKEN";
/// First line of every file this module writes, so stale ones can be removed
/// without touching a user's hand-written files.
pub const GENERATED_MARK: &str = "# generated by n8 ferricula discovery — do not edit, it is rewritten at launch";
/// Where a bridge finds the identity's local inference service, as a container sees it.
const OLLAMA_CONTAINER_URL: &str = "http://host.docker.internal:11434";
/// Container HOME; `data_home` on the host maps here.
const CONTAINER_HOME: &str = "/opt/nemesis8";

/// How an identity is reached by the agent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Transport {
    /// Streamable-HTTP MCP served by the container.
    Http,
    /// The identity's stdio bridge script, run by the container's Python.
    Bridge,
}

/// One discovered identity container.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Identity {
    /// The `ferricula.identity` label, verbatim.
    pub name: String,
    /// Container name without the leading slash.
    pub container: String,
    /// Docker state: `running`, `exited`, …
    pub state: String,
    /// Host port the identity is published on.
    pub host_port: u16,
    pub mcp_path: String,
    /// Host path of the stdio bridge script, when labelled.
    pub bridge: Option<PathBuf>,
    pub token_env: String,
    pub health_path: String,
    /// From `GET /health`, when the probe succeeded.
    pub agent_id: Option<String>,
    /// From `GET /health`: `paused`, `active`, …
    pub mode: Option<String>,
    /// HTTP status of an unauthenticated `POST /mcp`, when probed. 404 means
    /// the running image has no MCP route.
    pub mcp_status: Option<u16>,
}

impl Identity {
    /// The MCP server name written into agent configs: lowercase, `[a-z0-9_-]`.
    pub fn server_name(&self) -> String {
        sanitize_name(&self.name)
    }

    /// The identity's base URL as a container sees it.
    pub fn container_base_url(&self) -> String {
        format!("http://host.docker.internal:{}", self.host_port)
    }

    /// The MCP endpoint as a container sees it.
    pub fn container_url(&self) -> String {
        format!("{}{}", self.container_base_url(), self.mcp_path)
    }

    /// The MCP endpoint as the host sees it.
    pub fn host_url(&self) -> String {
        format!("http://127.0.0.1:{}{}", self.host_port, self.mcp_path)
    }

    pub fn is_running(&self) -> bool {
        self.state == "running"
    }

    /// Bridge when the container has no MCP route (or was not probed) and a
    /// bridge script exists; otherwise http.
    pub fn transport(&self) -> Transport {
        let route_missing = matches!(self.mcp_status, None | Some(404));
        match &self.bridge {
            Some(p) if route_missing && p.is_file() => Transport::Bridge,
            _ => Transport::Http,
        }
    }

    /// The `mcp_tools` entry that gives an agent this identity for a launch.
    pub fn tool_entry(&self) -> String {
        match self.transport() {
            Transport::Http => self.server_name(),
            Transport::Bridge => self.bridge_file_name(),
        }
    }

    /// Does this workspace's `mcp_tools` opt into the identity? Any of the
    /// identity's names counts: the server name, its `ferricula-` alias, or
    /// the bridge file.
    pub fn opted_in(&self, mcp_tools: &[String]) -> bool {
        let name = self.server_name();
        let alias = format!("ferricula-{name}");
        let bridge = self.bridge_file_name();
        mcp_tools.iter().any(|t| *t == name || *t == alias || *t == bridge)
    }

    /// File name of the generated http server TOML.
    pub fn toml_file_name(&self) -> String {
        format!("ferricula-{}.toml", self.server_name())
    }

    /// File name of the generated bridge wrapper.
    pub fn bridge_file_name(&self) -> String {
        format!("ferricula-{}.py", self.server_name())
    }

    /// Token file name under `<home>/.n8/ferricula/`.
    pub fn token_file_name(&self) -> String {
        format!("{}.token", self.server_name())
    }

    /// The `mcp-servers/*.toml`-shaped definition for the http transport.
    /// `enabled_by_default` stays false: config generation adds every
    /// enabled-by-default registry server to every agent, and an identity is
    /// opt-in.
    pub fn toml(&self) -> String {
        format!(
            "{GENERATED_MARK}\n# identity {} · container {} · {}\n[server]\nname = \"{}\"\naliases = [\"ferricula-{}\"]\nurl = \"{}\"\ntransport = \"http\"\nbearer_token_env = \"{}\"\nenabled_by_default = false\n",
            self.name,
            self.container,
            self.agent_id.as_deref().unwrap_or("agent id unknown"),
            self.server_name(),
            self.server_name(),
            self.container_url(),
            self.token_env,
        )
    }

    /// The bridge script with n8's header: the identity's base URL and the
    /// inference URL as a container sees them, and the token file n8 wrote.
    /// `setdefault`, so a value already in the environment wins. The header
    /// goes after a shebang and after any `from __future__` lines, which
    /// Python requires first.
    pub fn bridge_wrapper(&self, source: &str) -> String {
        let header = format!(
            "{GENERATED_MARK}\n# identity {} · container {} · bridge {}\nimport os as _n8_os\n_n8_os.environ.setdefault(\"FERRICULA_BASE_URL\", \"{}\")\n_n8_os.environ.setdefault(\"OLLAMA_BASE_URL\", \"{OLLAMA_CONTAINER_URL}\")\n_n8_os.environ.setdefault(\"{}_FILE\", \"{}\")\n",
            self.name,
            self.container,
            self.bridge.as_deref().map(|p| p.display().to_string()).unwrap_or_default(),
            self.container_base_url(),
            self.token_env,
            format!("{CONTAINER_HOME}/.n8/ferricula/{}", self.token_file_name()),
        );
        let lines: Vec<&str> = source.lines().collect();
        // Insert after the last line the header may not precede.
        let mut at = 0;
        if lines.first().is_some_and(|l| l.starts_with("#!")) {
            at = 1;
        }
        if let Some(i) = lines.iter().rposition(|l| l.trim_start().starts_with("from __future__")) {
            at = at.max(i + 1);
        }
        let mut out = String::new();
        for l in &lines[..at] {
            out.push_str(l);
            out.push('\n');
        }
        out.push_str(&header);
        for l in &lines[at..] {
            out.push_str(l);
            out.push('\n');
        }
        out
    }
}

fn sanitize_name(raw: &str) -> String {
    let s: String = raw
        .to_lowercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' || c == '-' { c } else { '-' })
        .collect();
    s.trim_matches('-').to_string()
}

/// Is discovery on for this config? Default yes; `ferricula_discovery = false` turns it off.
pub fn enabled(config: &crate::config::Config) -> bool {
    config.integrations.ferricula_discovery.unwrap_or(true)
}

/// Give every discovered identity to every agent? Default no (opt-in per
/// workspace); `ferricula_auto_enable = true` turns it on.
pub fn auto_enable(config: &crate::config::Config) -> bool {
    config.integrations.ferricula_auto_enable.unwrap_or(false)
}

/// Turn Docker's container list into identities. Containers without the
/// identity label, or without any host port, are skipped.
pub fn from_summaries(containers: &[ContainerSummary]) -> Vec<Identity> {
    let mut out = Vec::new();
    for c in containers {
        let labels: HashMap<String, String> = c.labels.clone().unwrap_or_default();
        let Some(identity) = labels.get(LABEL_IDENTITY).map(|s| s.trim()).filter(|s| !s.is_empty()) else {
            continue;
        };
        let labelled_port = labels.get(LABEL_PORT).and_then(|p| p.trim().parse::<u16>().ok());
        let published_port = c
            .ports
            .as_ref()
            .map(|ports| ports.iter().filter_map(|p| p.public_port).min())
            .unwrap_or(None);
        let Some(host_port) = labelled_port.or(published_port) else {
            continue;
        };
        let container = c
            .names
            .as_ref()
            .and_then(|n| n.first())
            .map(|n| n.trim_start_matches('/').to_string())
            .or_else(|| c.id.as_ref().map(|i| i.chars().take(12).collect()))
            .unwrap_or_else(|| "unknown".to_string());
        let bridge = labels
            .get(LABEL_BRIDGE)
            .map(|p| p.trim())
            .filter(|p| !p.is_empty())
            .map(|p| {
                let path = PathBuf::from(p);
                if path.is_absolute() {
                    path
                } else {
                    match labels.get(LABEL_COMPOSE_DIR) {
                        Some(dir) => PathBuf::from(dir).join(path),
                        None => path,
                    }
                }
            });
        out.push(Identity {
            name: identity.to_string(),
            container,
            state: c.state.clone().unwrap_or_default().to_lowercase(),
            host_port,
            mcp_path: labels
                .get(LABEL_PATH)
                .map(|p| p.trim().to_string())
                .filter(|p| p.starts_with('/'))
                .unwrap_or_else(|| "/mcp".to_string()),
            bridge,
            token_env: labels
                .get(LABEL_TOKEN_ENV)
                .map(|p| p.trim().to_string())
                .filter(|p| !p.is_empty())
                .unwrap_or_else(|| DEFAULT_TOKEN_ENV.to_string()),
            health_path: labels
                .get(LABEL_HEALTH)
                .map(|p| p.trim().to_string())
                .filter(|p| p.starts_with('/'))
                .unwrap_or_else(|| "/health".to_string()),
            agent_id: None,
            mode: None,
            mcp_status: None,
        });
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

/// Ask the Docker API for every container carrying the identity label. Empty
/// when the daemon is unreachable or nothing is labelled.
pub async fn discover(docker: &bollard::Docker) -> Vec<Identity> {
    use bollard::container::ListContainersOptions;
    let mut filters: HashMap<String, Vec<String>> = HashMap::new();
    filters.insert("label".to_string(), vec![LABEL_IDENTITY.to_string()]);
    match docker
        .list_containers(Some(ListContainersOptions::<String> {
            all: true,
            filters,
            ..Default::default()
        }))
        .await
    {
        Ok(list) => from_summaries(&list),
        Err(e) => {
            tracing::debug!("ferricula discovery: docker list failed: {e}");
            Vec::new()
        }
    }
}

/// Fill `agent_id` / `mode` from the health route and `mcp_status` from an
/// unauthenticated `POST` to the MCP path (host side, 400 ms each). A failed
/// probe leaves the field `None`; the identity is still available — the
/// agent's MCP client reports the real error at call time.
pub fn probe(id: &mut Identity) {
    let hostport = format!("127.0.0.1:{}", id.host_port);
    if let Some((_, body)) = http_request("GET", &hostport, &id.health_path, 400) {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&body) {
            id.agent_id = v.get("agent_id").and_then(|s| s.as_str()).map(str::to_string);
            id.mode = v.get("mode").and_then(|s| s.as_str()).map(str::to_string);
        }
    }
    id.mcp_status = http_request("POST", &hostport, &id.mcp_path, 400).map(|(status, _)| status);
}

/// Minimal one-shot request; returns the status and the body's JSON object
/// text (or an empty string when there is none).
fn http_request(method: &str, hostport: &str, path: &str, timeout_ms: u64) -> Option<(u16, String)> {
    use std::io::{Read, Write};
    let addr: std::net::SocketAddr = hostport.parse().ok()?;
    let timeout = std::time::Duration::from_millis(timeout_ms);
    let mut stream = std::net::TcpStream::connect_timeout(&addr, timeout).ok()?;
    stream.set_read_timeout(Some(timeout)).ok()?;
    stream.set_write_timeout(Some(timeout)).ok()?;
    let body = if method == "POST" { "{}" } else { "" };
    let req = format!(
        "{method} {path} HTTP/1.1\r\nHost: {hostport}\r\nAccept: application/json\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
        body.len()
    );
    stream.write_all(req.as_bytes()).ok()?;
    let mut raw = Vec::new();
    let _ = stream.read_to_end(&mut raw);
    let text = String::from_utf8_lossy(&raw);
    let (head, body) = text.split_once("\r\n\r\n")?;
    let status: u16 = head.split_whitespace().nth(1)?.parse().ok()?;
    let json = match (body.find('{'), body.rfind('}')) {
        (Some(s), Some(e)) if e >= s => body[s..=e].to_string(),
        _ => String::new(),
    };
    Some((status, json))
}

/// What [`apply`] did, for the launch log.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Applied {
    /// `mcp_tools` entries enabled for this launch (opted in, or auto-enable).
    pub registered: Vec<String>,
    /// Identities kept available but not given to this agent (not opted in).
    pub available: Vec<String>,
    /// Generated files removed because their identity is gone or changed transport.
    pub removed: Vec<String>,
    /// Token env names of ENABLED identities set in neither the keychain nor the environment.
    pub missing_tokens: Vec<String>,
}

/// Keep every RUNNING identity's definition current and clean up after gone
/// ones, then enable the ones this workspace opted into (or all, with
/// `ferricula_auto_enable`). Writes into `data_home` (the volume every
/// container mounts as HOME): `.nemesis8/mcp/ferricula-<name>.toml` for http,
/// `mcp/ferricula-<name>.py` for bridge, `.n8/ferricula/<name>.token` from the
/// keychain when the token is set. Enabling puts the transport's entry on
/// `config.mcp_tools` (replacing whichever of the identity's names the user
/// wrote) and the token env on `config.env.env_imports`.
pub fn apply(config: &mut crate::config::Config, data_home: &Path, identities: &[Identity]) -> Applied {
    apply_with(config, data_home, identities, &|name| {
        crate::secrets::get(name).ok().flatten().or_else(|| std::env::var(name).ok())
    })
}

/// [`apply`] with the token lookup injected (tests).
pub fn apply_with(
    config: &mut crate::config::Config,
    data_home: &Path,
    identities: &[Identity],
    token: &dyn Fn(&str) -> Option<String>,
) -> Applied {
    let mut applied = Applied::default();
    let servers_dir = crate::mcp_registry::host_user_mcp_dir(data_home);
    let tools_dir = data_home.join("mcp");
    let tokens_dir = data_home.join(".n8").join("ferricula");
    let give_all = auto_enable(config);
    let running: Vec<&Identity> = identities.iter().filter(|i| i.is_running()).collect();

    // Stale generated files first, so an identity that stopped (or changed
    // transport) disappears. Only files carrying our mark are ever removed.
    let keep_toml: Vec<String> = running
        .iter()
        .filter(|i| i.transport() == Transport::Http)
        .map(|i| i.toml_file_name())
        .collect();
    let keep_py: Vec<String> = running
        .iter()
        .filter(|i| i.transport() == Transport::Bridge)
        .map(|i| i.bridge_file_name())
        .collect();
    applied.removed.extend(remove_stale(&servers_dir, ".toml", &keep_toml));
    applied.removed.extend(remove_stale(&tools_dir, ".py", &keep_py));

    for id in running {
        let entry = match id.transport() {
            Transport::Http => {
                if std::fs::create_dir_all(&servers_dir).is_err()
                    || !write_if_changed(&servers_dir.join(id.toml_file_name()), &id.toml())
                {
                    continue;
                }
                id.server_name()
            }
            Transport::Bridge => {
                let Some(source) = id.bridge.as_ref().and_then(|p| std::fs::read_to_string(p).ok()) else {
                    continue;
                };
                if std::fs::create_dir_all(&tools_dir).is_err()
                    || !write_if_changed(&tools_dir.join(id.bridge_file_name()), &id.bridge_wrapper(&source))
                {
                    continue;
                }
                id.bridge_file_name()
            }
        };
        // The token file is kept current whether or not this agent gets the
        // identity, so opting in later needs no relaunch of anything else.
        let token_present = match token(&id.token_env) {
            Some(t) if !t.trim().is_empty() => {
                if std::fs::create_dir_all(&tokens_dir).is_ok() {
                    let _ = write_if_changed(&tokens_dir.join(id.token_file_name()), t.trim());
                }
                true
            }
            _ => false,
        };

        if !give_all && !id.opted_in(&config.mcp_tools) {
            applied.available.push(id.server_name());
            continue;
        }
        // Enabled: one entry, the right one for this transport, in place of
        // whichever of the identity's names the workspace wrote.
        let name = id.server_name();
        let alias = format!("ferricula-{name}");
        let bridge_file = id.bridge_file_name();
        config.mcp_tools.retain(|t| *t != name && *t != alias && *t != bridge_file);
        config.mcp_tools.push(entry.clone());
        if !config.env.env_imports.contains(&id.token_env) {
            config.env.env_imports.push(id.token_env.clone());
        }
        if !token_present && !applied.missing_tokens.contains(&id.token_env) {
            applied.missing_tokens.push(id.token_env.clone());
        }
        applied.registered.push(entry);
    }
    applied
}

/// Did this module write `path`? (The mark sits on line 1, or line 2 after a shebang.)
pub fn is_generated_file(path: &Path) -> bool {
    std::fs::read_to_string(path)
        .map(|s| s.lines().take(8).any(|l| l == GENERATED_MARK))
        .unwrap_or(false)
}

/// The identity name a generated file belongs to, from its header line
/// (`# identity <name> · …`). `None` for files this module did not write.
pub fn identity_of_generated(path: &Path) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    if !text.lines().take(8).any(|l| l == GENERATED_MARK) {
        return None;
    }
    text.lines()
        .take(10)
        .find_map(|l| l.strip_prefix("# identity "))
        .and_then(|rest| rest.split(" · ").next())
        .map(|s| sanitize_name(s.trim()))
        .filter(|s| !s.is_empty())
}

/// Remove generated `ferricula-*<ext>` files in `dir` that are not in `keep`.
fn remove_stale(dir: &Path, ext: &str, keep: &[String]) -> Vec<String> {
    let mut removed = Vec::new();
    let Ok(rd) = std::fs::read_dir(dir) else {
        return removed;
    };
    for entry in rd.flatten() {
        let fname = entry.file_name().to_string_lossy().to_string();
        if !fname.starts_with("ferricula-") || !fname.ends_with(ext) || keep.contains(&fname) {
            continue;
        }
        if is_generated_file(&entry.path()) && std::fs::remove_file(entry.path()).is_ok() {
            removed.push(fname);
        }
    }
    removed
}

/// Write only on change: these dirs are bind mounts every container reads.
fn write_if_changed(path: &Path, content: &str) -> bool {
    if std::fs::read_to_string(path).ok().as_deref() == Some(content) {
        return true;
    }
    std::fs::write(path, content).is_ok()
}

/// The launch-time step: discover, probe, apply, and say what happened.
/// No-op when discovery is off. Returns the identities for callers that
/// display them.
pub async fn discover_and_apply(
    docker: &bollard::Docker,
    data_home: &Path,
    config: &mut crate::config::Config,
) -> Vec<Identity> {
    if !enabled(config) {
        return Vec::new();
    }
    let mut identities = discover(docker).await;
    // The probes are plain blocking sockets with short timeouts; keep them
    // off the async worker.
    identities = tokio::task::spawn_blocking(move || {
        for id in identities.iter_mut().filter(|i| i.is_running()) {
            probe(id);
        }
        identities
    })
    .await
    .unwrap_or_default();
    let applied = apply(config, data_home, &identities);
    for name in &applied.removed {
        tracing::info!("integration: ferricula identity gone or changed, removed {name}");
    }
    for id in identities.iter().filter(|i| i.is_running()) {
        let how = match id.transport() {
            Transport::Http => format!("http {}", id.container_url()),
            Transport::Bridge => format!("stdio bridge {}", id.bridge_file_name()),
        };
        let name = id.server_name();
        if applied.available.contains(&name) {
            tracing::info!(
                "integration: ferricula identity {} available via {} (mode {}); not given to this agent — add `{}` to mcp_tools to opt in",
                id.name,
                how,
                id.mode.as_deref().unwrap_or("unknown"),
                name
            );
        } else {
            tracing::info!(
                "integration: ferricula identity {} → MCP server `{}` via {} (mode {}, token env {})",
                id.name,
                name,
                how,
                id.mode.as_deref().unwrap_or("unknown"),
                id.token_env
            );
        }
    }
    for env in &applied.missing_tokens {
        eprintln!(
            "[nemesis8] warning: ferricula identity token `{env}` is set neither in the keychain nor this \
             environment — the agent will reach the identity unauthenticated. Store it with `n8 secrets set {env}`."
        );
    }
    identities
}

#[cfg(test)]
mod tests {
    use super::*;
    use bollard::models::{Port, PortTypeEnum};

    fn summary(name: &str, state: &str, labels: &[(&str, &str)], ports: &[(u16, Option<u16>)]) -> ContainerSummary {
        ContainerSummary {
            id: Some("2d406c35aff7deadbeef".into()),
            names: Some(vec![format!("/{name}")]),
            state: Some(state.into()),
            labels: Some(labels.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()),
            ports: Some(
                ports
                    .iter()
                    .map(|(private, public)| Port {
                        ip: Some("127.0.0.1".into()),
                        private_port: *private,
                        public_port: *public,
                        typ: Some(PortTypeEnum::TCP),
                    })
                    .collect(),
            ),
            ..Default::default()
        }
    }

    fn steve_summary() -> ContainerSummary {
        summary(
            "steve-jobs-v2-test",
            "running",
            &[
                ("com.docker.compose.service", "steve"),
                ("com.docker.compose.project.working_dir", "C:\\proj\\ferricula_v2"),
                ("ferricula.identity", "steve"),
                ("ferricula.mcp_port", "18875"),
                ("ferricula.mcp_path", "/mcp"),
                ("ferricula.token_env", "FERRICULA_OPERATOR_TOKEN"),
            ],
            &[(8875, Some(18875))],
        )
    }

    fn steve() -> Identity {
        from_summaries(&[steve_summary()]).remove(0)
    }

    fn temp_home(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("n8-ferricula-{tag}-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn labelled_containers_become_identities_and_the_rest_are_skipped() {
        let list = vec![
            steve_summary(),
            summary("n8-fun-lark", "running", &[("nemesis8.agent", "true")], &[]),
            summary("no-port", "running", &[("ferricula.identity", "x")], &[]),
        ];
        let ids = from_summaries(&list);
        assert_eq!(ids.len(), 1);
        let s = &ids[0];
        assert_eq!(s.name, "steve");
        assert_eq!(s.container, "steve-jobs-v2-test");
        assert_eq!(s.host_port, 18875);
        assert_eq!(s.mcp_path, "/mcp");
        assert_eq!(s.bridge, None);
        assert_eq!(s.token_env, "FERRICULA_OPERATOR_TOKEN");
        assert_eq!(s.health_path, "/health");
        assert!(s.is_running());
        assert_eq!(s.container_url(), "http://host.docker.internal:18875/mcp");
        assert_eq!(s.host_url(), "http://127.0.0.1:18875/mcp");
        // No bridge: http regardless of the route probe.
        assert_eq!(s.transport(), Transport::Http);
        assert_eq!(s.tool_entry(), "steve");
    }

    #[test]
    fn port_falls_back_to_the_lowest_published_port_and_defaults_fill_in() {
        let list = vec![summary(
            "wren",
            "running",
            &[("ferricula.identity", "Wren Two")],
            &[(9000, None), (8875, Some(18900)), (8876, Some(18901))],
        )];
        let ids = from_summaries(&list);
        assert_eq!(ids.len(), 1);
        assert_eq!(ids[0].host_port, 18900);
        assert_eq!(ids[0].server_name(), "wren-two");
        assert_eq!(ids[0].toml_file_name(), "ferricula-wren-two.toml");
        assert_eq!(ids[0].bridge_file_name(), "ferricula-wren-two.py");
    }

    #[test]
    fn a_relative_bridge_label_resolves_under_the_compose_project_dir() {
        let rel = summary(
            "steve",
            "running",
            &[
                ("ferricula.identity", "steve"),
                ("ferricula.bridge", "scripts/steve_mcp_bridge.py"),
                ("com.docker.compose.project.working_dir", "C:\\proj\\ferricula_v2"),
            ],
            &[(8875, Some(18875))],
        );
        let id = from_summaries(&[rel]).remove(0);
        assert_eq!(id.bridge, Some(PathBuf::from("C:\\proj\\ferricula_v2").join("scripts/steve_mcp_bridge.py")));
        let abs = summary(
            "steve",
            "running",
            &[("ferricula.identity", "steve"), ("ferricula.bridge", "/srv/bridge.py")],
            &[(8875, Some(18875))],
        );
        assert_eq!(from_summaries(&[abs]).remove(0).bridge, Some(PathBuf::from("/srv/bridge.py")));
    }

    #[test]
    fn toml_is_an_opt_in_registry_server_def_marked_as_generated() {
        let mut s = steve();
        s.agent_id = Some("ferricula-stevejobs".into());
        let toml = s.toml();
        assert!(toml.starts_with(GENERATED_MARK));
        let def: crate::mcp_def::McpServerDef = toml::from_str(&toml).expect("parses as a server def");
        assert_eq!(def.server.name, "steve");
        assert_eq!(def.server.url.as_deref(), Some("http://host.docker.internal:18875/mcp"));
        assert_eq!(def.server.bearer_token_env.as_deref(), Some("FERRICULA_OPERATOR_TOKEN"));
        assert_eq!(def.server.aliases, vec!["ferricula-steve"]);
        assert!(!def.server.is_stdio());
        // Never always-on: config generation would hand it to every agent.
        assert!(!def.server.enabled_by_default);
    }

    #[test]
    fn bridge_wrapper_keeps_shebang_and_future_imports_first_and_names_its_identity() {
        let mut s = steve();
        s.bridge = Some(PathBuf::from("C:\\proj\\scripts\\steve_mcp_bridge.py"));
        let source = "#!/usr/bin/env python3\n\"\"\"doc\"\"\"\nfrom __future__ import annotations\nimport sys\nprint(sys.argv)\n";
        let wrapped = s.bridge_wrapper(source);
        let lines: Vec<&str> = wrapped.lines().collect();
        assert_eq!(lines[0], "#!/usr/bin/env python3");
        assert_eq!(lines[1], "\"\"\"doc\"\"\"");
        assert_eq!(lines[2], "from __future__ import annotations");
        assert_eq!(lines[3], GENERATED_MARK);
        assert!(wrapped.contains("_n8_os.environ.setdefault(\"FERRICULA_BASE_URL\", \"http://host.docker.internal:18875\")"));
        assert!(wrapped.contains("_n8_os.environ.setdefault(\"OLLAMA_BASE_URL\", \"http://host.docker.internal:11434\")"));
        assert!(wrapped.contains("_n8_os.environ.setdefault(\"FERRICULA_OPERATOR_TOKEN_FILE\", \"/opt/nemesis8/.n8/ferricula/steve.token\")"));
        assert!(wrapped.ends_with("print(sys.argv)\n"));
        // Plain script: the header goes first, after nothing.
        let plain = s.bridge_wrapper("import os\n");
        assert!(plain.starts_with(GENERATED_MARK));
        assert!(plain.ends_with("import os\n"));
        // The picker reads the identity back out of a generated file.
        let home = temp_home("ident");
        let wrapper = home.join("ferricula-steve.py");
        std::fs::write(&wrapper, &wrapped).unwrap();
        assert_eq!(identity_of_generated(&wrapper).as_deref(), Some("steve"));
        let toml_path = home.join("ferricula-steve.toml");
        std::fs::write(&toml_path, s.toml()).unwrap();
        assert_eq!(identity_of_generated(&toml_path).as_deref(), Some("steve"));
        let mine = home.join("ferricula-mine.py");
        std::fs::write(&mine, "import os\n").unwrap();
        assert_eq!(identity_of_generated(&mine), None);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn opt_in_names_cover_server_alias_and_bridge_file() {
        let s = steve();
        assert!(!s.opted_in(&["nuts-files".to_string()]));
        assert!(s.opted_in(&["steve".to_string()]));
        assert!(s.opted_in(&["ferricula-steve".to_string()]));
        assert!(s.opted_in(&["ferricula-steve.py".to_string()]));
    }

    #[test]
    fn apply_http_keeps_the_identity_available_until_the_workspace_opts_in() {
        let home = temp_home("http");
        let servers = crate::mcp_registry::host_user_mcp_dir(&home);
        std::fs::create_dir_all(&servers).unwrap();
        // A hand-written file with the ferricula- prefix must survive.
        std::fs::write(servers.join("ferricula-mine.toml"), "[server]\nname = \"mine\"\nurl = \"http://x/mcp\"\n").unwrap();
        // A stale generated one must go.
        std::fs::write(servers.join("ferricula-old.toml"), format!("{GENERATED_MARK}\n[server]\nname = \"old\"\n")).unwrap();
        let lookup = |name: &str| (name == "FERRICULA_OPERATOR_TOKEN").then(|| "hyp-operator-token".to_string());

        // Default: available, not enabled. Files and token are kept current anyway.
        let mut config = crate::config::Config::default();
        config.mcp_tools.push("nuts-files".into());
        let applied = apply_with(&mut config, &home, &[steve()], &lookup);
        assert!(applied.registered.is_empty());
        assert_eq!(applied.available, vec!["steve"]);
        assert_eq!(applied.removed, vec!["ferricula-old.toml"]);
        assert!(applied.missing_tokens.is_empty());
        assert!(servers.join("ferricula-steve.toml").is_file());
        assert!(servers.join("ferricula-mine.toml").is_file());
        assert!(!servers.join("ferricula-old.toml").exists());
        assert_eq!(
            std::fs::read_to_string(home.join(".n8").join("ferricula").join("steve.token")).unwrap(),
            "hyp-operator-token"
        );
        assert_eq!(config.mcp_tools, vec!["nuts-files"]);
        assert!(config.env.env_imports.is_empty());

        // Opted in by name: enabled, token env imported, idempotent.
        config.mcp_tools.push("steve".into());
        let applied = apply_with(&mut config, &home, &[steve()], &lookup);
        assert_eq!(applied.registered, vec!["steve"]);
        assert!(applied.available.is_empty());
        assert_eq!(config.mcp_tools, vec!["nuts-files", "steve"]);
        assert_eq!(config.env.env_imports, vec!["FERRICULA_OPERATOR_TOKEN"]);
        let again = apply_with(&mut config, &home, &[steve()], &lookup);
        assert_eq!(again.registered, vec!["steve"]);
        assert_eq!(config.mcp_tools, vec!["nuts-files", "steve"]);
        assert_eq!(config.env.env_imports, vec!["FERRICULA_OPERATOR_TOKEN"]);

        // Opted in by alias: normalised to the server name.
        let mut by_alias = crate::config::Config::default();
        by_alias.mcp_tools.push("ferricula-steve".into());
        apply_with(&mut by_alias, &home, &[steve()], &lookup);
        assert_eq!(by_alias.mcp_tools, vec!["steve"]);

        // Auto-enable gives it to every agent without listing it.
        let mut all = crate::config::Config::default();
        all.integrations.ferricula_auto_enable = Some(true);
        let applied = apply_with(&mut all, &home, &[steve()], &lookup);
        assert_eq!(applied.registered, vec!["steve"]);
        assert_eq!(all.mcp_tools, vec!["steve"]);

        // Missing token is only reported for an ENABLED identity.
        let mut quiet = crate::config::Config::default();
        assert!(apply_with(&mut quiet, &home, &[steve()], &|_| None).missing_tokens.is_empty());
        let mut loud = crate::config::Config::default();
        loud.mcp_tools.push("steve".into());
        assert_eq!(apply_with(&mut loud, &home, &[steve()], &|_| None).missing_tokens, vec!["FERRICULA_OPERATOR_TOKEN"]);

        // Stopped identity: nothing enabled, and its generated file is removed.
        let mut stopped = steve();
        stopped.state = "exited".into();
        let mut fresh = crate::config::Config::default();
        fresh.mcp_tools.push("steve".into());
        let gone = apply_with(&mut fresh, &home, &[stopped], &lookup);
        assert!(gone.registered.is_empty());
        assert_eq!(gone.removed, vec!["ferricula-steve.toml"]);
        assert_eq!(fresh.mcp_tools, vec!["steve"], "the workspace's own list is left alone");
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn apply_bridge_maps_the_opted_in_name_to_the_wrapper_and_flips_back_to_http() {
        let home = temp_home("bridge");
        let script = home.join("steve_mcp_bridge.py");
        std::fs::write(&script, "#!/usr/bin/env python3\nimport os\nprint(os.environ.get('FERRICULA_BASE_URL'))\n").unwrap();
        let mut id = steve();
        id.bridge = Some(script.clone());
        id.mcp_status = Some(404); // the running image has no MCP route
        assert_eq!(id.transport(), Transport::Bridge);
        assert_eq!(id.tool_entry(), "ferricula-steve.py");
        let lookup = |_: &str| Some("tok".to_string());

        // The user opts in by the identity's name; the launch gets the wrapper.
        let mut config = crate::config::Config::default();
        config.mcp_tools.push("steve".into());
        let applied = apply_with(&mut config, &home, &[id.clone()], &lookup);
        assert_eq!(applied.registered, vec!["ferricula-steve.py"]);
        let wrapper = home.join("mcp").join("ferricula-steve.py");
        let text = std::fs::read_to_string(&wrapper).unwrap();
        assert!(text.lines().nth(1) == Some(GENERATED_MARK), "{text}");
        assert!(text.contains("FERRICULA_BASE_URL"));
        assert!(text.ends_with("print(os.environ.get('FERRICULA_BASE_URL'))\n"));
        assert!(!crate::mcp_registry::host_user_mcp_dir(&home).join("ferricula-steve.toml").exists());
        assert_eq!(config.mcp_tools, vec!["ferricula-steve.py"]);
        assert_eq!(config.env.env_imports, vec!["FERRICULA_OPERATOR_TOKEN"]);

        // Not opted in: the wrapper is still written (available), nothing enabled.
        let mut other = crate::config::Config::default();
        let applied = apply_with(&mut other, &home, &[id.clone()], &lookup);
        assert!(applied.registered.is_empty());
        assert_eq!(applied.available, vec!["steve"]);
        assert!(other.mcp_tools.is_empty());

        // The container was recreated with an MCP route: http takes over, the
        // wrapper is cleaned up, and the opted-in name maps to the server.
        id.mcp_status = Some(401);
        assert_eq!(id.transport(), Transport::Http);
        let mut config = crate::config::Config::default();
        config.mcp_tools.push("ferricula-steve.py".into());
        let flipped = apply_with(&mut config, &home, &[id.clone()], &lookup);
        assert_eq!(flipped.registered, vec!["steve"]);
        assert_eq!(flipped.removed, vec!["ferricula-steve.py"]);
        assert!(!wrapper.exists());
        assert!(crate::mcp_registry::host_user_mcp_dir(&home).join("ferricula-steve.toml").is_file());
        assert_eq!(config.mcp_tools, vec!["steve"]);

        // A bridge label whose file is missing falls back to http too.
        id.mcp_status = Some(404);
        id.bridge = Some(home.join("nope.py"));
        assert_eq!(id.transport(), Transport::Http);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[tokio::test]
    async fn discovery_can_be_switched_off_without_touching_docker() {
        let mut config = crate::config::Config::default();
        assert!(enabled(&config));
        assert!(!auto_enable(&config));
        config.integrations.ferricula_discovery = Some(false);
        assert!(!enabled(&config));
        // A client pointed at nothing: with discovery off it is never used.
        let docker = bollard::Docker::connect_with_http("http://127.0.0.1:1", 1, bollard::API_DEFAULT_VERSION).unwrap();
        let dir = std::env::temp_dir().join(format!("n8-ferricula-off-{}", uuid::Uuid::new_v4()));
        let ids = discover_and_apply(&docker, &dir, &mut config).await;
        assert!(ids.is_empty());
        assert!(config.mcp_tools.is_empty());
        assert!(!dir.exists());
    }

    #[tokio::test]
    async fn an_unreachable_daemon_discovers_nothing() {
        let docker = bollard::Docker::connect_with_http("http://127.0.0.1:1", 1, bollard::API_DEFAULT_VERSION).unwrap();
        assert!(discover(&docker).await.is_empty());
    }
}
