use crate::mcp_def::McpServerDef;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Directory inside the Docker image where socket-MCP TOMLs are stored.
const BUILTIN_MCP_DIR: &str = "/opt/defaults/mcp";

// Compiled-in socket-MCP TOMLs — available on the host binary even without the
// Docker image. GENERATED by build.rs from mcp/*.toml (mirrors providers/services).
include!(concat!(env!("OUT_DIR"), "/embedded_mcp_servers.rs"));

/// Registry of all known socket (HTTP/SSE) MCP servers (builtins + user-defined).
pub struct McpRegistry {
    servers: HashMap<String, McpServerDef>,
    aliases: HashMap<String, String>,
}

impl McpRegistry {
    /// Build from the builtin mcp dir (Docker image / dev override), else the
    /// compiled-in TOMLs, then overlay `~/.nemesis8/mcp/*.toml` (override/add,
    /// no rebuild).
    pub fn load() -> Self {
        let mut reg = Self {
            servers: HashMap::new(),
            aliases: HashMap::new(),
        };

        let builtin_dir = builtin_mcp_dir();
        if builtin_dir.is_dir() {
            reg.load_from_dir(&builtin_dir);
        } else {
            reg.load_embedded();
        }
        reg.load_user_servers();
        reg
    }

    fn insert(&mut self, def: McpServerDef) {
        let name = def.server.name.to_lowercase();
        for alias in &def.server.aliases {
            self.aliases.insert(alias.to_lowercase(), name.clone());
        }
        self.servers.insert(name, def);
    }

    fn load_embedded(&mut self) {
        for toml_str in EMBEDDED_MCP_SERVERS {
            match toml::from_str::<McpServerDef>(toml_str) {
                Ok(def) => self.insert(def),
                Err(e) => eprintln!("[nemesis8] warning: failed to parse embedded mcp server: {e}"),
            }
        }
    }

    fn load_from_dir(&mut self, dir: &Path) {
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(e) => {
                eprintln!("[nemesis8] warning: could not read mcp dir {}: {e}", dir.display());
                return;
            }
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "toml") {
                continue;
            }
            self.load_file(&path);
        }
    }

    fn load_file(&mut self, path: &Path) {
        match std::fs::read_to_string(path) {
            Ok(content) => match toml::from_str::<McpServerDef>(&content) {
                Ok(def) => self.insert(def),
                Err(e) => eprintln!("[nemesis8] warning: failed to parse {}: {e}", path.display()),
            },
            Err(e) => eprintln!("[nemesis8] warning: could not read {}: {e}", path.display()),
        }
    }

    fn load_user_servers(&mut self) {
        let user_dir = user_mcp_dir();
        if !user_dir.is_dir() {
            return;
        }
        let entries = match std::fs::read_dir(&user_dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "toml") {
                continue;
            }
            self.load_file(&path);
        }
    }

    /// Look up a server by name or alias (case-insensitive).
    pub fn get(&self, name: &str) -> Option<&McpServerDef> {
        let key = name.to_lowercase();
        self.servers
            .get(&key)
            .or_else(|| self.aliases.get(&key).and_then(|n| self.servers.get(n)))
    }

    /// Iterate all registered servers.
    pub fn all(&self) -> impl Iterator<Item = &McpServerDef> {
        self.servers.values()
    }

    /// All registered server names, sorted.
    pub fn names(&self) -> Vec<&str> {
        let mut names: Vec<&str> = self.servers.keys().map(|s| s.as_str()).collect();
        names.sort();
        names
    }
}

/// The user override dir: `~/.nemesis8/mcp`. In a container HOME=/opt/nemesis8,
/// so this is `/opt/nemesis8/.nemesis8/mcp` — the drop-a-TOML, no-rebuild path.
pub fn user_mcp_dir() -> PathBuf {
    dirs::home_dir()
        .map(|h| h.join(".nemesis8").join("mcp"))
        .unwrap_or_default()
}

/// Builtin mcp dir. Honors NEMESIS8_MCP_DIR (tests) then the image path.
fn builtin_mcp_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("NEMESIS8_MCP_DIR") {
        return PathBuf::from(dir);
    }
    PathBuf::from(BUILTIN_MCP_DIR)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn load_test_registry() -> McpRegistry {
        let mcp_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("mcp-servers");
        unsafe {
            std::env::set_var("NEMESIS8_MCP_DIR", &mcp_dir);
        }
        McpRegistry::load()
    }

    #[test]
    fn test_load_hyperia() {
        let reg = load_test_registry();
        let h = reg.get("hyperia").expect("hyperia in registry");
        assert!(h.server.url.contains("/mcp"));
        assert_eq!(h.server.bearer_token_env.as_deref(), Some("HYPERIA_AGENT_TOKEN"));
        assert!(reg.get("HYPERIA").is_some()); // case-insensitive
    }

    #[test]
    fn test_names_nonempty() {
        let reg = load_test_registry();
        assert!(reg.names().contains(&"hyperia"));
    }

    #[test]
    fn test_transport_auto_detect() {
        let reg = load_test_registry();
        // hyperia's URL ends in /mcp → streamable http
        assert_eq!(reg.get("hyperia").unwrap().server.resolved_transport(), "http");
    }
}
