//! Per-tool secret manifest, embedded from `MCP/*.py` `# n8:secrets` headers at
//! build time (build.rs). Lets the host — the Tools picker, the launcher, and
//! the scheduler — know which secrets each MCP tool needs (required vs optional)
//! WITHOUT reading the container image. Keyed by tool filename (e.g.
//! `"discord.py"`), matching the entries in a workspace's `mcp_tools`.
//!
//! Populate a tool's needs by adding one header line to its `.py`, e.g.:
//! `# n8:secrets required=DISCORD_BOT_TOKEN optional=DISCORD_CHANNEL_ID`

// GENERATED by build.rs: `const MCP_SECRETS: &[(&str, &[&str], &[&str])]` —
// (tool filename, required secret names, optional secret names).
include!(concat!(env!("OUT_DIR"), "/embedded_mcp_secrets.rs"));

type Entry = (&'static str, &'static [&'static str], &'static [&'static str]);

fn lookup(tool: &str) -> Option<&'static Entry> {
    MCP_SECRETS.iter().find(|(name, _, _)| *name == tool)
}

/// Required secret names for a tool filename (empty when the tool declares none
/// or isn't a `.py` tool).
pub fn required_for(tool: &str) -> &'static [&'static str] {
    lookup(tool).map(|(_, r, _)| *r).unwrap_or(&[])
}

/// Optional secret names for a tool filename.
pub fn optional_for(tool: &str) -> &'static [&'static str] {
    lookup(tool).map(|(_, _, o)| *o).unwrap_or(&[])
}

fn union_of<'a>(tools: &[String], pick: impl Fn(&str) -> &'static [&'static str]) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for t in tools {
        for s in pick(t) {
            if !out.iter().any(|x| x == s) {
                out.push((*s).to_string());
            }
        }
    }
    out
}

/// Required secret names across all given (enabled) tools — deduped, order-stable.
pub fn required_for_enabled(tools: &[String]) -> Vec<String> {
    union_of(tools, required_for)
}

/// Every secret name (required ∪ optional) across the given tools — deduped.
/// This is the set the launcher forwards keychain-first for enabled tools.
pub fn all_for_enabled(tools: &[String]) -> Vec<String> {
    let mut out = required_for_enabled(tools);
    for s in union_of(tools, optional_for) {
        if !out.contains(&s) {
            out.push(s);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_discord_manifest() {
        // Seeded from MCP/discord.py's `# n8:secrets` header.
        assert!(required_for("discord.py").contains(&"DISCORD_BOT_TOKEN"));
        assert!(optional_for("discord.py").contains(&"DISCORD_CHANNEL_ID"));
        assert!(required_for("does-not-exist.py").is_empty());
    }

    #[test]
    fn test_required_for_enabled_dedup() {
        // github.py and github_discussions.py both need GITHUB_TOKEN → one entry.
        let tools = vec!["github.py".to_string(), "github_discussions.py".to_string()];
        let req = required_for_enabled(&tools);
        assert_eq!(req.iter().filter(|s| *s == "GITHUB_TOKEN").count(), 1);
    }
}
