use crate::service_def::ServiceDef;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Directory inside the Docker image where service TOMLs are stored.
const BUILTIN_SERVICES_DIR: &str = "/opt/defaults/services";

// Compiled-in service TOMLs — available on the host binary even without the
// Docker image. GENERATED by build.rs from services/*.toml (mirrors providers).
include!(concat!(env!("OUT_DIR"), "/embedded_services.rs"));

/// Registry of all known dependency services (builtins + user-defined).
pub struct ServiceRegistry {
    services: HashMap<String, ServiceDef>,
}

impl ServiceRegistry {
    /// Build from the builtin services dir (Docker image / dev override), else
    /// the compiled-in TOMLs, then overlay `~/.nemesis8/services/*.toml`.
    pub fn load() -> Self {
        let mut reg = Self {
            services: HashMap::new(),
        };

        let builtin_dir = builtin_services_dir();
        if builtin_dir.is_dir() {
            reg.load_services_from_dir(&builtin_dir);
        } else {
            reg.load_embedded();
        }
        reg.load_user_services();
        reg
    }

    fn load_embedded(&mut self) {
        for toml_str in EMBEDDED_SERVICES {
            match toml::from_str::<ServiceDef>(toml_str) {
                Ok(def) => {
                    self.services.insert(def.service.name.to_lowercase(), def);
                }
                Err(e) => {
                    eprintln!("[nemesis8] warning: failed to parse embedded service: {e}");
                }
            }
        }
    }

    fn load_services_from_dir(&mut self, dir: &Path) {
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(e) => {
                eprintln!(
                    "[nemesis8] warning: could not read services dir {}: {e}",
                    dir.display()
                );
                return;
            }
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "toml") {
                continue;
            }
            self.load_service_file(&path);
        }
    }

    fn load_service_file(&mut self, path: &Path) {
        match std::fs::read_to_string(path) {
            Ok(content) => match toml::from_str::<ServiceDef>(&content) {
                Ok(def) => {
                    self.services.insert(def.service.name.to_lowercase(), def);
                }
                Err(e) => {
                    eprintln!("[nemesis8] warning: failed to parse {}: {e}", path.display());
                }
            },
            Err(e) => {
                eprintln!("[nemesis8] warning: could not read {}: {e}", path.display());
            }
        }
    }

    fn load_user_services(&mut self) {
        let user_dir = dirs::home_dir()
            .map(|h| h.join(".nemesis8").join("services"))
            .unwrap_or_default();
        if !user_dir.is_dir() {
            return;
        }
        let entries = match std::fs::read_dir(&user_dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "toml") {
                continue;
            }
            self.load_service_file(&path);
        }
    }

    /// Look up a service by name (case-insensitive).
    pub fn get(&self, name: &str) -> Option<&ServiceDef> {
        self.services.get(&name.to_lowercase())
    }

    /// Resolve a service name, with a helpful error listing the known ones.
    pub fn resolve(&self, name: &str) -> Result<&ServiceDef, String> {
        self.get(name).ok_or_else(|| {
            format!("unknown service '{}'. Available: {}", name, self.names().join(", "))
        })
    }

    /// Iterate all registered services.
    pub fn all(&self) -> impl Iterator<Item = &ServiceDef> {
        self.services.values()
    }

    /// All registered service names, sorted.
    pub fn names(&self) -> Vec<&str> {
        let mut names: Vec<&str> = self.services.keys().map(|s| s.as_str()).collect();
        names.sort();
        names
    }
}

/// Builtin services dir. Honors NEMESIS8_SERVICES_DIR (tests) then the image path.
fn builtin_services_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("NEMESIS8_SERVICES_DIR") {
        return PathBuf::from(dir);
    }
    PathBuf::from(BUILTIN_SERVICES_DIR)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn load_test_registry() -> ServiceRegistry {
        let services_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("services");
        unsafe {
            std::env::set_var("NEMESIS8_SERVICES_DIR", &services_dir);
        }
        ServiceRegistry::load()
    }

    #[test]
    fn test_load_ferricula() {
        let reg = load_test_registry();
        assert!(reg.get("ferricula").is_some());
        assert!(reg.get("FERRICULA").is_some()); // case-insensitive
    }

    #[test]
    fn test_resolve_error() {
        let reg = load_test_registry();
        let err = reg.resolve("nope").unwrap_err();
        assert!(err.contains("unknown service"));
        assert!(err.contains("ferricula"));
    }

    #[test]
    fn test_names_nonempty() {
        let reg = load_test_registry();
        assert!(reg.names().contains(&"ferricula"));
    }
}
